var files = [
    "images/1-Polar Code.png",
    "images/Agustus.jpg",
    "images/Drake.jpg",
    "images/Drip.jpg",
    "images/Fall.jpg",
    "images/Farewell.jpg",
    "images/Genji 2.0.jpg",
    "images/Genji.jpg",
    "images/Here Wall.jpg",
    "images/OK.jpg",
    "images/Old Times.jpg",
    "images/Polar Code 2.png",
    "images/Reap.jpg",
    "images/Red Death.jpg",
    "images/Ronin.jpg",
    "images/Runegard.jpg",
    "images/Shadow.jpg",
    "images/The Last.jpg",
    "images/The Request.jpg",
    "images/The Test.jpg",
];
var names = [
    "1-Polar Code",
    "Agustus",
    "Drake",
    "Drip",
    "Fall",
    "Farewell",
    "Genji 2.0",
    "Genji",
    "Here Wall",
    "OK",
    "Old Times",
    "Polar Code 2",
    "Reap",
    "Red Death",
    "Ronin",
    "Runegard",
    "Shadow",
    "The Last",
    "The Request",
    "The Test",
];
